In [2]:
"""
Created on Sat Nov 17 10:14:00 2018

@author: alexandremendes
"""

'\nCreated on Sat Nov 17 10:14:00 2018\n\n@author: alexandremendes\n'

## Library

In [3]:
import numpy as np
from statsmodels.api import OLS
import pandas as pd

## Dataframe

In [4]:
df = pd.read_excel('./Harmon.xlsx')

In [5]:
df

,TIME,Sales,CP,CP(t-1),CP(t-2),DA,DA(t-1),DA(t-2),SeasIndx
0,1,425075,75253,0,0,457732,352872,304004,113
1,2,315305,15036,75253,0,254396,457732,352872,98
2,3,367286,134440,15036,75253,259952,254396,457732,102
3,4,429432,119740,134440,15036,267368,259952,254396,107
4,5,347874,135590,119740,134440,158504,267368,259952,119
5,6,435529,189636,135590,119740,430012,158504,267368,104
6,7,299403,9308,189636,135590,388516,430012,158504,107
7,8,296505,41099,9308,189636,225616,388516,430012,81
8,9,426701,9391,41099,9308,1042304,225616,388516,113
9,10,329722,942,9391,41099,974092,1042304,225616,97
10,11,281783,1818,942,9391,301892,974092,1042304,95
11,12,166391,672,1818,942,76148,301892,974092,65
12,13,629404,548704,672,1818,0,76148,301892,113
13,14,263467,52819,548704,672,315196,0,76148,98
14,15,398320,2793,52819,548704,703624,315196,0,102
15,16,376569,27749,2793,52819,198464,703624,315196,107
16,17,444404,21887,27749,2793,478880,198464,703624,119
17,18,386986,1110,21887,27749,457172,478880,198464,104
18,19,414314,436,1110,21887,709480,457172,478880,107
19,20,253493,1407,436,1110,45380,709480,457172,81
20,21,484365,376650,1407,436,28080,45380,709480,113
21,22,305989,122906,376650,1407,111520,28080,45380,97
22,23,315407,15138,122906,376650,267200,111520,28080,95
23,24,182784,5532,15138,122906,354304,267200,111520,65
24,25,655748,544807,5532,15138,664712,354304,267200,113
25,26,270483,43704,544807,5532,536824,664712,354304,98
26,27,365058,5740,43704,544807,551560,536824,664712,102
27,28,313135,9614,5740,43704,150080,551560,536824,107
28,29,528210,1507,9614,5740,580800,150080,551560,119
29,30,379856,13620,1507,9614,435080,580800,150080,104
30,31,472058,101179,13620,1507,361144,435080,580800,107
31,32,254516,80309,101179,13620,97844,361144,435080,81
32,33,551354,335768,80309,101179,30372,97844,361144,113
33,34,335826,91710,335768,80309,150324,30372,97844,97
34,35,320408,9856,91710,335768,293044,150324,30372,95
35,36,276901,107172,9856,91710,162788,293044,150324,65
36,37,455136,299781,107172,9856,32532,162788,293044,113
37,38,247570,21218,299781,107172,23468,32532,162788,98
38,39,622204,157,21218,299781,4503456,23468,32532,102
39,40,429331,12961,157,21218,500904,4503456,23468,107
40,41,453156,333529,12961,157,0,500904,4503456,119
41,42,320103,178105,333529,12961,0,0,500904,104
42,43,451779,315564,178105,333529,46104,0,0,107
43,44,249482,80206,315564,178105,92252,46104,0,81
44,45,744583,5940,80206,315564,4869952,92252,46104,113
45,46,421186,36819,5940,80206,376556,4869952,92252,97
46,47,397367,234562,36819,5940,376556,376556,4869952,95
47,48,269096,71881,234562,36819,552536,376556,376556,65

## Question 1

In [8]:
def mult_lin_reg(y, x): # least square method
    model = OLS(y, x)
    result = model.fit()
    return print(result.summary())

##### CP & DA

In [7]:
y_CP_DA = df.Sales

In [10]:
x_CP_DA = df[['CP','DA','SeasIndx']]

In [11]:
mult_lin_reg(y_CP_DA,x_CP_DA)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.987
Model:                            OLS   Adj. R-squared:                  0.987
Method:                 Least Squares   F-statistic:                     1170.
Date:                Thu, 22 Nov 2018   Prob (F-statistic):           1.08e-42
Time:                        21:26:03   Log-Likelihood:                -582.50
No. Observations:                  48   AIC:                             1171.
Df Residuals:                      45   BIC:                             1177.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
CP             0.4389      0.052      8.415      0.000       0.334       0.544
DA             0.0798      0.008     10.275      0.000       0.064       0.095
SeasIndx    2996.3932    100.838     29.715      0.000    2793.296    3199.490
==============================================================================
Omnibus:                        1.169   Durbin-Watson:                   2.235
Prob(Omnibus):                  0.557   Jarque-Bera (JB):                0.844
Skew:                           0.325   Prob(JB):                        0.656
Kurtosis:                       2.974   Cond. No.                     1.55e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.55e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

##### CP & DA(t-1)

In [12]:
y_CP_DA_t_1 = df.Sales[:]

In [13]:
x_CP_DA_t_1 = df[['CP','DA(t-1)','SeasIndx']]

In [14]:
mult_lin_reg(y_CP_DA_t_1,x_CP_DA_t_1)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.958
Model:                            OLS   Adj. R-squared:                  0.955
Method:                 Least Squares   F-statistic:                     341.8
Date:                Thu, 22 Nov 2018   Prob (F-statistic):           5.73e-31
Time:                        21:27:21   Log-Likelihood:                -611.31
No. Observations:                  48   AIC:                             1229.
Df Residuals:                      45   BIC:                             1234.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
CP             0.3014      0.093      3.224      0.002       0.113       0.490
DA(t-1)        0.0079      0.014      0.571      0.571      -0.020       0.036
SeasIndx    3506.5239    177.619     19.742      0.000    3148.780    3864.267
==============================================================================
Omnibus:                       38.949   Durbin-Watson:                   2.358
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              121.955
Skew:                           2.163   Prob(JB):                     3.29e-27
Kurtosis:                       9.501   Cond. No.                     1.50e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.5e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

##### CP & DA(t-2)

In [16]:
y_CP_DA_t_2 = df.Sales[:]

In [17]:
x_CP_DA_t_2 = df[['CP','DA(t-2)','SeasIndx']]

In [18]:
mult_lin_reg(y_CP_DA_t_2,x_CP_DA_t_2)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.959
Model:                            OLS   Adj. R-squared:                  0.956
Method:                 Least Squares   F-statistic:                     347.7
Date:                Thu, 22 Nov 2018   Prob (F-statistic):           3.98e-31
Time:                        21:28:02   Log-Likelihood:                -610.92
No. Observations:                  48   AIC:                             1228.
Df Residuals:                      45   BIC:                             1233.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
CP             0.3136      0.093      3.357      0.002       0.125       0.502
DA(t-2)       -0.0143      0.014     -1.034      0.307      -0.042       0.014
SeasIndx    3602.2852    159.644     22.564      0.000    3280.745    3923.826
==============================================================================
Omnibus:                       35.195   Durbin-Watson:                   2.217
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               98.400
Skew:                           1.970   Prob(JB):                     4.29e-22
Kurtosis:                       8.804   Cond. No.                     1.36e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.36e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

#### DA & CP(t-1)

In [19]:
y_DA_CP_t_1 = df.Sales[:]

In [20]:
x_DA_CP_t_1 = df[['CP(t-1)','DA','SeasIndx']]

In [21]:
mult_lin_reg(y_DA_CP_t_1,x_DA_CP_t_1)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.973
Model:                            OLS   Adj. R-squared:                  0.971
Method:                 Least Squares   F-statistic:                     542.9
Date:                Thu, 22 Nov 2018   Prob (F-statistic):           2.49e-35
Time:                        21:28:43   Log-Likelihood:                -600.59
No. Observations:                  48   AIC:                             1207.
Df Residuals:                      45   BIC:                             1213.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
CP(t-1)       -0.2153      0.070     -3.083      0.003      -0.356      -0.075
DA             0.0579      0.011      5.290      0.000       0.036       0.080
SeasIndx    3773.6400    133.016     28.370      0.000    3505.732    4041.548
==============================================================================
Omnibus:                       14.343   Durbin-Watson:                   2.187
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               16.106
Skew:                           1.142   Prob(JB):                     0.000318
Kurtosis:                       4.684   Cond. No.                     1.41e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.41e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

#### DA & CP(t-2)

In [36]:
y_DA_CP_t_2 = df.Sales[2:]

In [37]:
x_DA_CP_t_2 = df[['CP(t-2)','DA']][2:]

In [51]:
mult_lin_reg(y_DA_CP_t_2,x_DA_CP_t_2)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.455
Model:                            OLS   Adj. R-squared:                  0.430
Method:                 Least Squares   F-statistic:                     18.35
Date:                Fri, 16 Nov 2018   Prob (F-statistic):           1.60e-06
Time:                        11:24:41   Log-Likelihood:                -644.91
No. Observations:                  46   AIC:                             1294.
Df Residuals:                      44   BIC:                             1297.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
CP(t-2)        0.8444      0.305      2.771      0.008       0.230       1.459
DA             0.1583      0.049      3.203      0.003       0.059       0.258
==============================================================================
Omnibus:                        8.043   Durbin-Watson:                   0.878
Prob(Omnibus):                  0.018   Jarque-Bera (JB):                7.011
Skew:                          -0.828   Prob(JB):                       0.0300
Kurtosis:                       3.956   Cond. No.                         7.23
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### DA(t-1) & CP(t-1)

In [40]:
y_DA_t_1_CP_t_1 = df.Sales[1:]

In [41]:
x_DA_t_1_CP_t_1 = df[['CP(t-1)','DA(t-1)']][1:]

In [52]:
mult_lin_reg(y_DA_t_1_CP_t_1,x_DA_t_1_CP_t_1)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.393
Model:                            OLS   Adj. R-squared:                  0.366
Method:                 Least Squares   F-statistic:                     14.55
Date:                Fri, 16 Nov 2018   Prob (F-statistic):           1.34e-05
Time:                        11:25:27   Log-Likelihood:                -661.28
No. Observations:                  47   AIC:                             1327.
Df Residuals:                      45   BIC:                             1330.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
CP(t-1)        1.0059      0.271      3.710      0.001       0.460       1.552
DA(t-1)        0.1558      0.045      3.471      0.001       0.065       0.246
==============================================================================
Omnibus:                        2.682   Durbin-Watson:                   1.841
Prob(Omnibus):                  0.262   Jarque-Bera (JB):                1.938
Skew:                          -0.489   Prob(JB):                        0.379
Kurtosis:                       3.177   Cond. No.                         6.08
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### DA(t-1) & CP(t-2)

In [53]:
y_DA_t_1_CP_t_2 = df.Sales[2:]

In [55]:
x_DA_t_1_CP_t_2 = df[['CP(t-2)','DA(t-1)']][2:]

In [56]:
mult_lin_reg(y_DA_t_1_CP_t_2,x_DA_t_1_CP_t_2)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.450
Model:                            OLS   Adj. R-squared:                  0.425
Method:                 Least Squares   F-statistic:                     18.02
Date:                Fri, 16 Nov 2018   Prob (F-statistic):           1.92e-06
Time:                        11:26:21   Log-Likelihood:                -645.10
No. Observations:                  46   AIC:                             1294.
Df Residuals:                      44   BIC:                             1298.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
CP(t-2)        1.1880      0.267      4.443      0.000       0.649       1.727
DA(t-1)        0.1362      0.043      3.133      0.003       0.049       0.224
==============================================================================
Omnibus:                        4.674   Durbin-Watson:                   1.266
Prob(Omnibus):                  0.097   Jarque-Bera (JB):                3.725
Skew:                          -0.682   Prob(JB):                        0.155
Kurtosis:                       3.290   Cond. No.                         6.27
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### DA(t-2) & CP(t-1)

In [58]:
y_DA_t_2_CP_t_1 = df.Sales[2:]

In [59]:
x_DA_t_2_CP_t_1 = df[['CP(t-1)','DA(t-2)']][2:]

In [60]:
mult_lin_reg(y_DA_t_2_CP_t_1,x_DA_t_2_CP_t_1)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.386
Model:                            OLS   Adj. R-squared:                  0.358
Method:                 Least Squares   F-statistic:                     13.83
Date:                Fri, 16 Nov 2018   Prob (F-statistic):           2.19e-05
Time:                        11:27:56   Log-Likelihood:                -647.65
No. Observations:                  46   AIC:                             1299.
Df Residuals:                      44   BIC:                             1303.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
CP(t-1)        0.9692      0.275      3.520      0.001       0.414       1.524
DA(t-2)        0.1537      0.046      3.375      0.002       0.062       0.246
==============================================================================
Omnibus:                        3.095   Durbin-Watson:                   1.399
Prob(Omnibus):                  0.213   Jarque-Bera (JB):                2.415
Skew:                          -0.559   Prob(JB):                        0.299
Kurtosis:                       3.094   Cond. No.                         6.11
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

#### DA(t-2) & CP((t-2)

In [15]:
y_DA_t_2_CP_t_2 = df.Sales

In [16]:
x_DA_t_2_CP_t_2 = df[['CP(t-2)','DA(t-2)','SeasIndx']]

In [17]:
mult_lin_reg(y_DA_t_2_CP_t_2,x_DA_t_2_CP_t_2)

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.949
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     279.0
Date:                Fri, 23 Nov 2018   Prob (F-statistic):           4.44e-29
Time:                        09:37:11   Log-Likelihood:                -615.96
No. Observations:                  48   AIC:                             1238.
Df Residuals:                      45   BIC:                             1244.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
CP(t-2)        0.0781      0.099      0.787      0.435      -0.122       0.278
DA(t-2)       -0.0003      0.015     -0.017      0.987      -0.031       0.031
SeasIndx    3790.9285    186.800     20.294      0.000    3414.694    4167.163
==============================================================================
Omnibus:                       18.153   Durbin-Watson:                   2.556
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               22.566
Skew:                           1.379   Prob(JB):                     1.26e-05
Kurtosis:                       4.916   Cond. No.                     1.43e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.43e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

### Answer
CP & DA multiple linear regression display the best R-squared (ajusted or not), the smallest P-values & also the smallest IC

## Question 2

Sales = 11.909 + 1.4497 x CP + 0.2047 x DA

## Question 3

In [69]:
def sales_estimation(CP, DA, const, coeff_CP, coeff_DA):
    return const + coeff_CP * CP + coeff_DA * DA

In [71]:
cste = 11.909

coeff_CP_point = 1.4497
coeff_CP_min = 1.092
coeff_CP_max = 1.807
CP_case = 100000

coeff_DA_point = 0.2047     
coeff_DA_min = 0.146
coeff_DA_max = 0.264
DA_case = 500000

In [79]:
sales_point = sales_estimation(CP_case, DA_case, cste, coeff_CP_point, coeff_DA_point)
sales_min = sales_estimation(CP_case, DA_case, cste, coeff_CP_min, coeff_DA_min)
sales_max = sales_estimation(CP_case, DA_case, cste, coeff_CP_max, coeff_DA_max)

print('sales estimation is equal to $', sales_point, 'with an IC [',sales_min,',',sales_max,'] for 5% error')

sales estimation is equal to $ 247331.909 with an IC [ 182211.909 , 312711.909 ] for 5% error

## Question 4
???